### ISSUE TITLE
GBDK-2020 can not find SDCC binaries in Fedora

### ISSUE THREAD

**Issue by DaSalba** [Zal0/gbdk-2020#101]
I am running the latest version of Fedora (33). I installed SDCC from the repositories using:

`sudo dnf install sdcc`

When I tried to compile GBDK-2020 I got several errors, because the Makefile could not find the SDCC binaries. I browsed `/usr/bin` and discovered that they had been installed using different names; instead of `sdcc` I got `sdcc-sdcc`, instead of `sdar` I got `sdcc-sdar`, and such (each binary had `sdcc` prepended to its name). The binaries I have are:

```
sdcc-as2gbmap
sdcc-makebin
sdcc-packihx
sdcc-s51
sdcc-sdar
sdcc-sdas390
sdcc-sdas6808
sdcc-sdas8051
sdcc-sdasgb
sdcc-sdaspdk13
sdcc-sdaspdk14
sdcc-sdaspdk15
sdcc-sdasrab
sdcc-sdasstm8
sdcc-sdastlcs90
sdcc-sdasz80
sdcc-sdcc
sdcc-sdcdb
sdcc-sdcpp
sdcc-sdld
sdcc-sdld6808
sdcc-sdldgb
sdcc-sdldpdk
sdcc-sdldstm8
sdcc-sdldz80
sdcc-sdnm
sdcc-sdobjcopy
sdcc-sdranlib
sdcc-shc08
sdcc-spdk
sdcc-sstm8
sdcc-stlcs
sdcc-sz80
```
I solved this problem by creating symlinks to the tools GBDK needs, but I suggest that some check is added to the Makefile so, if this is the case, it can locate the correct binaries.

**Comment by bbbbbr** [comment]
Is the Fedora package version of sdcc new enough? It looks like it's 4.0.3
https://koji.fedoraproject.org/koji/buildinfo?buildID=1511036

But for GBDK 2020 version 4.0.4 #11952 or later should be used.

**Comment by DaSalba** [comment]
Indeed, I am using the precompiled release for doing actual stuff, but it is just a matter of time before the SDCC in the repos gets updated, so I think this should be taken into account. I just wanted to test if it worked already.

This is in no way critical or urgent, but someday Fedora users may want to compile GBDK without bothering to download and install libraries manually. It puzzled me that the binaries would be named like this (not GBDK's fault of course).

**Comment by bbbbbr** [comment]
You may find the normally named binaries under /usr/libexec/sdcc and the ones in /usr/bin to just be symlinked. Fedora users should try that for their SDCCDIR instead.

The package lists them here
https://koji.fedoraproject.org/koji/rpminfo?fileStart=50&rpmID=21584520&fileOrder=name&buildrootOrder=-id&buildrootStart=0#filelist

The backstory: they were concerned about the names being too generic and conflicting with others in /usr/bin. Not a particularly straightforward solution to the problem.
https://bugzilla.redhat.com/show_bug.cgi?id=233385
https://src.fedoraproject.org/rpms/sdcc

**Comment by DaSalba** [comment]
You are right. Neither `ls` nor `find` show that they are symlinks, they must be hard links then.

Well, I guess we can close this; if any other Fedora user gets this same error he will be able to find this issue and know what to do (set `SDCCDIR` to `/usr/libexec/sdcc/`).
