### ISSUE TITLE
Update version reported by Lcc

### ISSUE THREAD

**Issue by bbbbbr** [Zal0/gbdk-2020#102]
Well, it's not 2001 anymore. Any objections to updating the version, date and author reported by lcc? 

Does anything rely on or test for that specific string?

`v 1.6 2001/10/28 18:38:13 michaelh Exp $";`

How about this, and perhaps building the date of compilation into the string?
`v 2.0 2020/12/01 18:38:13 gbdk2020 Exp $";`

**Comment by untoxa** [comment]
i agree

**Comment by untoxa** [comment]
https://github.com/Zal0/gbdk-2020/pull/110
