### ISSUE TITLE
is __mullong meant to be excluded?

### ISSUE THREAD

**Issue by gingemonster** [Zal0/gbdk-2020#108]
https://github.com/Zal0/gbdk-2020/blob/0dd6c6f48fd095bfb710e6adda71b6bdc573bcf3/gbdk-lib/libc/_mullong.c

this code seems to be in GBDK but if I try and multiple two long values in my code I get:

?ASlink-Warning-Undefined Global '__mullong' referenced by module 'main'

When I try and compile using lcc

**Comment by untoxa** [comment]
it is not included, because there is no asm implementation for GBZ80 at the moment. C implementation is huge and very slow.

**Comment by untoxa** [comment]
for the same reason floating point math is excluded too

**Comment by gingemonster** [comment]
ok thanks for confirming

**Comment by untoxa** [comment]
oh! sorry, i thought about long long. :) that broke down because functions were renamed in recent SDCC builds. i fixed that: https://github.com/Zal0/gbdk-2020/commit/e0f9f1f817ccd1944a1d63aa1d604d008ef34e1f
