### ISSUE TITLE
race condition in .set_xy_tt

### ISSUE THREAD

**Issue by jkotlinski** [Zal0/gbdk-2020#117]
WAIT_STAT
	LD	A, (HL+)
	LD	(BC), A

stat register should be rechecked post-write.
also, interrupts should be disabled during check, write and re-check.

**Comment by untoxa** [comment]
no

**Comment by jkotlinski** [comment]
? surely it can't be good that the function randomly fails?

**Comment by untoxa** [comment]
please, investigate first, before submitting a bug. if you are sure "function randomly fails" - submit a minimal example that demonstrates that. also use latest library from the trunk. thank you.

**Comment by jkotlinski** [comment]
:)  Of course I investigate first. Why would I care if there is not an actual problem?

To review the code,

1. there is a verification that H-blank or V-blank is active
2. new value is written to VRAM

Problem is that there is no guarantee that the condition verified in step 1 is still valid during step 2. Because H-blank/V-blank may be exited before write happens.

**Comment by untoxa** [comment]
minimal example that demonstrates problem

**Comment by jkotlinski** [comment]
It is difficult to reliably demonstrate the problem, since it is a race
condition. Perhaps it is enough to consider the following sequence of
events?

1. WAIT_STAT ensures being in H/V-blank
2. An interrupt triggers (e.g. JOY or SIO)
3. As interrupt handler exits, we are no longer in H/V-blank
4. The VRAM write fails

**Comment by untoxa** [comment]
No

**Comment by bbbbbr** [comment]
> It is difficult to reliably demonstrate the problem, since it is a race condition. Perhaps it is enough to consider the following sequence of events? 1. WAIT_STAT ensures being in H/V-blank 2. An interrupt triggers (e.g. JOY or SIO) 3. As interrupt handler exits, we are no longer in H/V-blank 4. The VRAM write fails
SGSILSYRAU3ANCNFSM4VXK336Q> .

The interrupt handlers were changed a while back to check STAT before exiting, so that should not be happening.
https://github.com/Zal0/gbdk-2020/blame/develop/gbdk-lib/libc/gb/crt0.s#L76
