### ISSUE TITLE
Simplify debug mode

### ISSUE THREAD

**Issue by basxto** [Zal0/gbdk-2020#118]
It would be easier if `lcc` would just accept `--debug` and then set `--debug` for the compiler and `-y` for the linker

**Comment by bbbbbr** [comment]
Seems reasonable. Probably easy to implement.

In keeping with current lcc convention, probably just a single char before the option `-debug` (`-tempdir`, `-target`, etc).

Should it also turn on .map and .noi output? (`-Wl-m -Wl-j`)

**Comment by basxto** [comment]
`.noi` output could be interesting for those who want to convert that into `.sym` and debug with a different debugger
