### ISSUE TITLE
stdint.h, limits.h missing

### ISSUE THREAD

**Issue by JL2210** [Zal0/gbdk-2020#12]
I recently made an optimized `abs` routine in assembly to replace the one written in C. The tests I made use the constants `INT_MIN` and `INT_MAX` from `limits.h`, but `limits.h` is not available (as well as `stdint.h`).

Is there a way to fix this? Am I missing something?

**Comment by basxto** [comment]
gbdk uses https://github.com/Zal0/gbdk-2020/blob/develop/gbdk-lib/include/asm/types.h instead of `stdint.h`

We could just define `stdint.h` and `limits.h`, though

**Comment by untoxa** [comment]
the most part of standard library should be migrated from the library, that comes with SDCC4. limits.h and stdint.h are among those files.

**Comment by untoxa** [comment]
fixed, we can close that.

**Comment by JL2210** [comment]
@untoxa What commit was this fixed in?

**Comment by untoxa** [comment]
https://github.com/Zal0/gbdk-2020/commit/0c933bc573dd9e7b8b327b70d91fb0df39498cf2
