### ISSUE TITLE
Can't compile for arm

### ISSUE THREAD

**Issue by MA-Designs** [Zal0/gbdk-2020#121]
I want to use this on an server made from a raspberry pi 3b+ running Ubuntu server 20.10 or Raspbian.  SDCC cannot be compiled by me.  Maybe I'm stupid, idunno.  Any chance for an arm binary release?  Please?

gcc is installed but sdcc confire cpp fails sanity check...

**Comment by bbbbbr** [comment]
It's easier and probably better to use SDCC snapshot builds than building sdcc yourself.
http://sdcc.sourceforge.net/snap.php

They have some ARM options under "other builds"
- Ubuntu on ARMv8 (aarch64-unknown-linux-gnu)
- Rasbian on ARMv6 armhf (armv6l-unknown-linux-gnueabihf)

**Comment by untoxa** [comment]
sorry, that's not an issue of GBDK
