### ISSUE TITLE
Docs URL does not appear to work

### ISSUE THREAD

**Issue by AndroidKitKat** [Zal0/gbdk-2020#129]
The URL listed on the README is for https://zal0.github.io/gbdk-2020/docs/api which is a 404. Wondering if this could get fixed?

**Comment by bbbbbr** [comment]
@Zal0 If I remember right you might be the only one able to change this?

The www root in the repo settings needs to change from `/docs/` to just `/`. 

Ref: https://github.com/Zal0/gbdk-2020/pull/125#issuecomment-770469701

**Comment by Zal0** [comment]
Ok, done
