### ISSUE TITLE
Merge or upstream libc where applicable

### ISSUE THREAD

**Issue by basxto** [Zal0/gbdk-2020#130]
Merging files (.asm and .c) from gbdk-2020's [libc](https://github.com/Zal0/gbdk-2020/tree/develop/gbdk-lib/libc) with the one of [sdcc](https://sourceforge.net/p/sdcc/code/HEAD/tree/trunk/sdcc/device/lib/) could reduce time and effort needed for maintaining them.

**ASM:** SDCC (`lib/gbz80/`) does contain gameboy specific assembly files, in those cases we should upstream our (`libc/asm/gbz80/`) changes, unless the ones in sdcc are better, but I do not expect that.

**C:** For cases where both use c files, sdcc's should be used and maybe improved. They do allow target specific inline assembly and code chunks selected with preprocessor switches.

I don't know if it is possible to selectively override some functions from sdcc and fall back it's standard library in all other cases. That should be investigated.

This is in general about investigating, comparing and for asm also counting the cycles.

**Comment by untoxa** [comment]
Just make pr’s with files you want to merge into the gbdk-2020 repo.
