### ISSUE TITLE
<gb/drawing.h>bug

### ISSUE THREAD

**Issue by sttng** [Zal0/gbdk-2020#137]
Seems drawing.c has a bug with line function.

line(50,50,23,22); is for example not drawing correctly. It seems 23,22 is correctly targeted, but 50,50 is not.

Tested with rgbds-0.4.2-win64

**Comment by untoxa** [comment]
fixed: https://github.com/Zal0/gbdk-2020/commit/2a8675de7eb3a0ee513dcbc8cc2d9fe4f32535b0
