### ISSUE TITLE
Info for Build on Raspberry Pi

### ISSUE THREAD

**Issue by NitroProp** [Zal0/gbdk-2020#140]
Hello I would like to compile for Raspberry Pi, actually i'm using a pi 400, but i do not know how retrive the required version of sdcc, on the repository is writter that is required: sdcc nightlies from 4.0.7 #12016 onwards but on the link provided i didn't found this version. Can someone help me out ?

**Comment by bbbbbr** [comment]
They have some ARM options under "other builds"
    Ubuntu on ARMv8 (aarch64-unknown-linux-gnu)
    Rasbian on ARMv6 armhf (armv6l-unknown-linux-gnueabihf)
