### ISSUE TITLE
Makefile:220: *** SDCCDIR is undefined.  Stop. Raspbian on Raspberry Pi 4

### ISSUE THREAD

**Issue by NitroProp** [Zal0/gbdk-2020#145]
Hello, I'm building on Raspberry Pi 4 everything has been carefully configured in order to compile correctly, after the download and installation of SDCC in the home folder I exported variables like so:

export PATH=$PATH:/home/pi/sdcc/bin
export SDCCDIR=/home/pi/sdcc

As you can see this is the printenv result:

SDCCDIR=/home/pi/sdcc
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/home/pi/sdcc/bin

This is the content of the home folder:

pi@raspberrypi:~ $ ls
gbdk-2020-4.0.2  sdcc  sdcc-snapshot-armv6l-unknown-linux-gnueabihf-20210121-12016.tar.bz2

when I try to sudo make this is the error:

Makefile:220: *** SDCCDIR is undefined.  Stop.

This has been performed on a fresh new Raspbian installation on a Raspberry Pi 4.

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux

I hope the information i provided are enought to replicate the issue because I do not know why the makefile is unable to locate SDCC even if the SDCCDIR has been properly configured.

Thank You

**Comment by untoxa** [comment]
why you do sudo make? Just make.
