### ISSUE TITLE
Custom font no longer working (-1 offset)

### ISSUE THREAD

**Issue by DaSalba** [Zal0/gbdk-2020#146]
I had a custom font implemented and working OK. Today I recompiled my project after several months, using the latest version of GBDK-2020, and found out that everything still works except for my custom font. The texts appear garbled.

Eventually I discovered that the ROM is now using the character immediately before the one I want; e.g. if I want to type a "Q", a "P" appears instead. I seem to recall that GBDK applied a +1 offset for some reason (the first tile was a blank space perhaps?), and I had to take this into account when creating the font. Has the font system been changed, and this offset removed?

**Comment by untoxa** [comment]
yes, this offset was removed. seems that it was useless.

**Comment by DaSalba** [comment]
From my notes: 

> GBDK always loads font data at tile 1, leaving 0 blank, so the first tile would actually be the second (0x01). Usually, fonts use tile 0xFF as white space, because GBDK adds 1 and gets 0x00, which is that first blank tile. When we fill the map, we have to take  into account that GBDK will add 1 to the tile number we give.

Indeed, it seems better now, though now I will have to fix every value of my custom font map...

**Comment by untoxa** [comment]
Sorry about that, but you also seem to be the only one who bothered himself creating a custom font. ;)

**Comment by DaSalba** [comment]
Well, the best way of learning is by doing :P
