### ISSUE TITLE
Getting started url 404s

### ISSUE THREAD

**Issue by djmcgill** [Zal0/gbdk-2020#147]
```
A good place to start is the [Getting Started Section](https://zal0.github.io/gbdk-2020/docs/api/docs_getting_started.html)
```
This link 404s. I'm not actually sure what the correct link should be, since https://zal0.github.io/gbdk-2020/docs/api works fine.

It looks like the templating doesn't quite work for some reason?
![image](https://user-images.githubusercontent.com/1290757/108792334-ed23be00-7578-11eb-84aa-cda07ceb6413.png)

**Comment by bbbbbr** [comment]
It's because updated docs have not been merged into the Master branch, and the repo is set to serve the Master branch on github.io.

When that is done a link like this will be available:
https://bbbbbr.github.io/gbdk-2020/docs/api/docs_getting_started.html

**Comment by djmcgill** [comment]
Makes sense, thanks.
