### ISSUE TITLE
Printing characters with printf()

### ISSUE THREAD

**Issue by DaSalba** [Zal0/gbdk-2020#149]
Perhaps I am missing something, but this code:

```
#include <gb/gb.h>
#include <stdio.h>

main(void)
{
	UINT8 number1 = 1;
	UINT8 number2 = 2;
	UINT8 number3 = 3;
	
	UINT8 char1 = 'A';
	UINT8 char2 = 'B';
	UINT8 char3 = 'C';
	
	printf("HELLO\n");
	printf("%u + %u = %u\n", number1, number2, number3);
	printf("%c + %c = %c\n", char1, char2, char3);
	
	return 0;
}
```
Should print:

```
HELLO
1 + 2 = 3
A + B = C
```

But instead it prints:

```
HELLO
1 + 2 = 3
A +   = B
```

I have tried also with `char` and `INT8`. What might be the issue?

**Comment by untoxa** [comment]
`printf("%c + %c = %c\n", (UINT8)char1, (UINT8)char2, (UINT8)char3);`
http://sdcc.sourceforge.net/doc/sdccman.pdf chapter 3.5.10

**Comment by DaSalba** [comment]
I thought it was a GBDK thing, not SDCC... Should have suspected so. Thanks!

**Comment by untoxa** [comment]
it's not an issue, it is intended behaviour
