### ISSUE TITLE
Getting Started page in readme is a dead link

### ISSUE THREAD

**Issue by anistarafdar** [Zal0/gbdk-2020#154]
"A good place to start is the [Getting Started Section](https://zal0.github.io/gbdk-2020/docs/api/docs_getting_started.html)"

this link currently goes to a 404, was the link changed? thanks

**Comment by bbbbbr** [comment]
See: https://github.com/Zal0/gbdk-2020/issues/147

I will get fixed in the next release when develop merges to master. That should be soon if all goes well.

In the mean time my repo usually serves pre-release docs:
https://bbbbbr.github.io/gbdk-2020/docs/api/docs_getting_started.html

**Comment by anistarafdar** [comment]
thank you for the help
