### ISSUE TITLE
Suggestion: Drawing.h / Drawing.s -  Drawing Mode: Clear affected tile

### ISSUE THREAD

**Issue by sttng** [Zal0/gbdk-2020#156]
It would be useful (for me) to add a drawing mode which basically clears (i.e. sets white) the complete affected tile before adding pixels to an affected tile. I hope it is understandable.

Currently when you draw for ex. 2 lines, the new line is drawn over the old line (i.e the old line is not cleared). 
Of course one could set_bkg_data to clear the whole screen before drawing the new line, but this is quite inefficient. I assume handling this mode at drawing.s makes more sense. I assume with this mode there could be even some bit-operations saved in drawing.s

Thanks for consideration.

**Comment by bbbbbr** [comment]
Not sure if it is practical for your application, but have you considered saving the coordinates of your previous line and "undrawing" it?  (either with the desired background color, or changing to the XOR pen)

https://zal0.github.io/gbdk-2020/docs/api/drawing_8h.html#ac9f0e5e503be3fe11f09b28252187c55

**Comment by sttng** [comment]
Yeah, I did that. Practically drawing the old line again in white color. That is way too slow. Might check if XOR is drawing mode is faster, but i doubt it will make a significant difference.

**Comment by untoxa** [comment]
your suggestion is too peculiar to be included into base GBDK library.
