### ISSUE TITLE
Drawing.h / Drawing.s: Coordinates outside the screen area

### ISSUE THREAD

**Issue by sttng** [Zal0/gbdk-2020#159]
It seems like drawing, plotting,... outside the screen coordinates (x>159, y > 143) will not draw at the correct background coordinates, but just wrap around to the next tile of the screen. 

For example `plot_point(160, 0);` will effectively create a dot at screen coord (0, 7) and not at background coord(160,0).

Of course the developer can implement checks or implement clipping algorithms (i.e. Cohen–Sutherland) but the question is if the framework should not check either for illegal values or if it should not draw within the background coordinate system.

**Comment by untoxa** [comment]
yes, that is a known limitation. that is for speed, additional checks will slow down everything even more.

**Comment by sttng** [comment]
I can totally understand the limitation and speed / efficiency considerations, but I guess then it should be part of the documentation that x,y max are 159, 143 (screen coords.). Its not that explicitly documented as of now.

**Comment by untoxa** [comment]
yes, i agree. @bbbbbr, please add this info.
