### ISSUE TITLE
warning 158: overflow in implicit constant conversion

### ISSUE THREAD

**Issue by sttng** [Zal0/gbdk-2020#165]
I have a relatively large lookuptable defined 

```
const INT16 myLUT[1280] = 
{
13,
214,
415,
............
};
```
and get this warning:

`warning 158: overflow in implicit constant conversion`

The generated code seems to work however.

**Comment by untoxa** [comment]
One of the values in your array exceed maximum value for signed int16. Also i suggest to declare your array const, or else it will be constructed in wram with huge initialization code.
