### ISSUE TITLE
memcpy() and memset() not working

### ISSUE THREAD

**Issue by DaSalba** [Zal0/gbdk-2020#17]
Taking the following minimal example:

```
#include <gb/gb.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

typedef struct ExampleStruct
{
	UINT8 number1;
	UINT8 number2;
};

void main(void)
{
	struct ExampleStruct struct1;
	struct1.number1 = 10;
	struct1.number2 = 20;
	printf("number1: %u\n", struct1.number1);
	printf("number2: %u\n", struct1.number2);
	
	struct ExampleStruct struct2;
	struct2 = struct1;
	printf("number1: %u\n", struct2.number1);
	printf("number2: %u\n", struct2.number2);
	
	memset(&struct1, 0, sizeof(struct ExampleStruct));
	printf("number1: %u\n", struct1.number1);
	printf("number2: %u\n", struct1.number2);
}
```

Compiling fails with:

> warning 112: function 'memset' implicit declaration
> error 101: too many parameters

Linking fails with:

> ?ASlink-Warning-Undefined Global ___memcpy referenced by module

The same code works correctly when using [gbdk-n](https://github.com/andreasjhkarlsson/gbdk-n).

Strangely enough, `memcpy(0, 0, 0)` links correctly.

`malloc()` does not work either but I seem to recall that it was broken, right?

**Comment by JL2210** [comment]
`memcpy(0, 0, 0)` is probably being optimized away by SDCC.
