### ISSUE TITLE
lcc determines it's directory wrongly

### ISSUE THREAD

**Issue by basxto** [Zal0/gbdk-2020#29]
Calling lcc as `gbdk-2020/build/gbdk/bin//lcc` does not work, but there shouldn't be a difference to `gbdk-2020/build/gbdk/bin/lcc`

**Comment by basxto** [comment]
https://github.com/Zal0/gbdk-2020/blob/v3.2/gbdk-support/lcc/gb.c#L281 is causing this

**Comment by Zal0** [comment]
why do you want to call lcc that way?

**Comment by basxto** [comment]
That’s just something that tends to happen when you concatenate variables to paths, you often add extra `/` for safety reasons when variables can be changed by the user

**Comment by untoxa** [comment]
fixed in 4.0 release
