### ISSUE TITLE
Strange error with banks and printf()

### ISSUE THREAD

**Issue by DaSalba** [Zal0/gbdk-2020#34]
So I'm quite puzzled by this one, taking this minimal example:

**include.h:**
```
#ifndef INCLUDE
#define INCLUDE

#include <gb/gb.h>

extern UINT8 bank;
extern UINT8 next;

void bank1_init();
void bank1_test();

void bank2_init();
void bank2_test();

#endif
```

**bank1.c:**
```
#include <gb/gb.h>
#include <stdio.h>

#include "include.h"

#pragma bank 1

void
bank1_init()
{
	printf("Welcome to bank 1.\nPRESS START\n");
}

void
bank1_test()
{
	if (joypad() & J_START)
	{
		printf("Good work!\n");
		next = 2;
	}
}
```

**bank2.c:**
```
#include <gb/gb.h>
#include <stdio.h>

#include "include.h"

#pragma bank 2

void
bank2_init()
{
	printf("Welcome to bank 2.\nPRESS SELECT\n");
}

void
bank2_test()
{
	if (joypad() & J_SELECT)
	{
		printf("Good work!\n");
		next = 1;
	}
}
```

**main.c:**
```
#include <gb/gb.h>
#include <stdio.h>

#include "include.h"

UINT8 bank;
UINT8 next;

void
main(void)
{
	bank = 1;
	next = 1;
	
	//printf("HELLO.\n");
	SWITCH_ROM_MBC5(bank);
	bank1_init();
	
	while (1)
	{
		wait_vbl_done();
		
		switch (bank)
		{
			case 1:
				bank1_test();
				break;
				
			case 2:
				bank2_test();
				break;
		}
		
		if (next != bank)
		{
			SWITCH_ROM_MBC5(next);
			
			switch (next)
			{
				case 1U:
					bank1_init();
					break;
					
				case 2U:
					bank2_init();
					break;
			}
			
			bank = next;
		}
	}
}

```

This program compiles OK (bank1.c goes to ROM bank 1 and bank2.c to bank 2) and it should work, but it doesn't. The strange thing is that, if we uncomment the line that says `printf("HELLO.\n");` (main.c), it works.

Also, I have tested it with past versions of GBDK-2020, and found that it works with release 3.0.1 (with the `printf` commented out, as it should).

Any explanation for this behavior?

Also, if I comment out the first bank switch, it stops working too. Shouldn't bank 1 be active by default?

**Comment by DaSalba** [comment]
Strange, the errors seem to have disappeared, despite having checked it 100 times before opening the issue. It all works now. Perhaps it was due to Linux updates that screwed it somehow the other day. I'll close this and put the blame on black magic.

**Comment by Zal0** [comment]
Thanks for letting me know
