### ISSUE TITLE
sdcc --debug switch breaks the far_fixer

### ISSUE THREAD

**Issue by untoxa** [Zal0/gbdk-2020#36]
if you set the --debug commandline switch for the SDCC, it emits additional info to object files:
`;!FILE build\ISO.c.asm
XL2
H 7 areas 929 global symbols
M ISO
O -mgbz80
S _r2 Ref0000
S _clear_map Ref0000
S _draw_to_shadow_XY Ref0000
`
so that comment in the first line breaks the far_fixer embedded into the linker, so we get this error:
`Error: Format(;!FILE) Only XL2 format is supported`
it takes the first string of a file as a file format definition, while it should take the first not empty and not commented out (e.g. begins with ";") string.

**Comment by untoxa** [comment]
https://github.com/Zal0/gbdk-2020/commit/ba7b6caf1eb57280203c45fc3f1ff033ed0ffcd4

**Comment by Zal0** [comment]
Thanks!
I forgot to close this one
