### ISSUE TITLE
LCC handles paths with spaces incorrectly in windows

### ISSUE THREAD

**Issue by untoxa** [Zal0/gbdk-2020#40]
if you try to build examples with gbdk in "C:\Program` Files (x86)" folder you get:

```
C:\Program` Files (x86)\gbdk\examples\gb>..\..\bin\lcc -Wa-l -Wl-m -Wl-j -c -o paint.o paint.c
..\..\bin\lcc: C:\Program: Invalid argument
```

that's because it does not escape paths that contain spaces with double quotes, like:

```"c:\program files (x86)\gbdk\bin\sdcc\bin\sdcc.exe"```

**Comment by Zal0** [comment]
This is finally fixed on Windows and macos. I haven't tested it on Linux, but it should work [too](https://github.com/Zal0/gbdk-2020/commit/7de93f62204b7e9ccb0b0c05e1d8121ab9524aea)
