### ISSUE TITLE
bsearch.c build error

### ISSUE THREAD

**Issue by ChaboCode** [Zal0/gbdk-2020#45]
Output:
=======
bsearch.c:33: syntax error: token -> 'const' ; column 10
bsearch.c:33: syntax error: token -> ')' ; column 37
bsearch.c:38: error 20: Undefined identifier 'c'
bsearch.c:40: error 20: Undefined identifier 'c'
bsearch.c:42: error 20: Undefined identifier 'left'
bsearch.c:42: error 20: Undefined identifier 'middle'
bsearch.c:46: error 20: Undefined identifier 'middle'
-:0: warning 154: converting integral to pointer without a cast
from type 'int fixed'
  to type 'void generic* fixed'
-:0: warning 85: in function bsearch unreferenced function argument : 'key'
-:0: warning 85: in function bsearch unreferenced function argument : 'base'
-:0: warning 85: in function bsearch unreferenced function argument : 'compar'
bsearch.c:49: syntax error: token -> 'return' ; column 7
../libc/rules-asxxxx.mk:7: recipe for target '../build/small/asxxxx/gbz80/bsearch.o' failed
make[2]: *** [../build/small/asxxxx/gbz80/bsearch.o] Error 1
Makefile:31: recipe for target 'ports' failed
make[1]: *** [ports] Error 2
Makefile:150: recipe for target 'gbdk-lib-build' failed
make: *** [gbdk-lib-build] Error 2

**Comment by drpaneas** [comment]
I have the same failure in openSUSE as well.

**Comment by untoxa** [comment]
what shows "sdcc -v" ?

**Comment by drpaneas** [comment]
```
SDCC : mcs51/z80/z180/r2k/r3ka/gbz80/tlcs90/ds390/pic16/pic14/TININative/ds400/hc08/s08/stm8 3.6.0 #9615 (Linux)
published under GNU General Public License (GPL)
```

**Comment by untoxa** [comment]
you need at least v. 4.0.0
