### ISSUE TITLE
`printf` works incorrectly on data types smaller than `int`

### ISSUE THREAD

**Issue by ISSOtm** [Zal0/gbdk-2020#47]
Reported by a user on the Discord server: `printf("%u\n", (UINT8)0);` prints a garbage value (3072 for them), but `printf("%u\n, (int)0);` works correctly.

This appears to stem from an incompatibility between the function's calling convention (preventing integer promotion) and the function's behavior (expecting promotion).

**Comment by spth** [comment]
See section 3.5.10, "Omitting promotion of arguments of vararg function" in the SDCC manual for details.

Short story: Omitting promotion here is an intended "feature" (non-standard-compliant behaviour). But when using an option such as --std-c89, --std-c95, --std-c11 or --std-c2x, SDCC will behave according to the standard and do the promotion.

**Comment by untoxa** [comment]
https://github.com/Zal0/gbdk-2020/commit/07acd8e12ade8747e0f16db8f04bb73eef876b5f#diff-e3b2ff2a1cdc6cd7501a63dcca5ee1fb
