### ISSUE TITLE
Building examples failing on Linux

### ISSUE THREAD

**Issue by Takuyax** [Zal0/gbdk-2020#49]
When I run make, to build the examples, I get the following output for each example (redundant lines redacted):

```../../bin/lcc -Wa-l -Wl-m -Wl-j -c -o galaxy.o galaxy.c
../../bin/lcc -Wa-l -Wl-m -Wl-j -o galaxy.gb galaxy.o
Error: Format(XL3) Only XL2 format is supported
Error: Format(XL3) Only XL2 format is supported
Error: Format(XL3) Only XL2 format is supported
[83 lines redacted]
Error: Format(XL3) Only XL2 format is supported
Error: Format(XL3) Only XL2 format is supported
WARNING: possibly wrote twice at addr 0 (00->00)
WARNING: possibly wrote twice at addr 10 (00->00)
WARNING: possibly wrote twice at addr 1d (00->10)
WARNING: possibly wrote twice at addr 40 (00->00)
WARNING: possibly wrote twice at addr 40 (00->00)
WARNING: possibly wrote twice at addr 48 (00->00)
WARNING: possibly wrote twice at addr 48 (00->00)
WARNING: possibly wrote twice at addr 48 (00->00)
WARNING: possibly wrote twice at addr 50 (00->00)
WARNING: possibly wrote twice at addr 50 (00->00)
WARNING: possibly wrote twice at addr 50 (00->00)
[56 lines redacted]
WARNING: possibly wrote twice at addr 1e0 (00->00)
ERROR: address overflow (addr c0bd >= 8000)
Makefile:37: recipe for target 'galaxy.gb' failed
make: *** [galaxy.gb] Error 1
```

I'm on Kubuntu 18.04 and used sdcc-snapshot-amd64-unknown-linux2.5-20200904-11846.tar.bz2 when building GBDK. I used GBDK release 3.2.

Any help would be appreciated.

**Comment by drpaneas** [comment]
This is a failure from opensuse leap 15.1

```c
bsearch.c:33: syntax error: token -> 'const' ; column 10
bsearch.c:33: syntax error: token -> ')' ; column 37
bsearch.c:38: error 20: Undefined identifier 'c'
bsearch.c:40: error 20: Undefined identifier 'c'
bsearch.c:42: error 20: Undefined identifier 'left'
bsearch.c:42: error 20: Undefined identifier 'middle'
bsearch.c:46: error 20: Undefined identifier 'middle'
-:0: warning 154: converting integral to pointer without a cast
from type 'int fixed'
  to type 'void generic* fixed'
-:0: warning 85: in function bsearch unreferenced function argument : 'key'
-:0: warning 85: in function bsearch unreferenced function argument : 'base'
-:0: warning 85: in function bsearch unreferenced function argument : 'compar'
bsearch.c:49: syntax error: token -> 'return' ; column 7
make[2]: *** [../libc/rules-asxxxx.mk:7: ../build/small/asxxxx/gbz80/bsearch.o] Error 1
make[1]: *** [Makefile:33: ports] Error 2
make: *** [Makefile:151: gbdk-lib-build] Error 2
```

**Comment by Sudospective** [comment]
I'm mostly curious as to why there aren't pre-built Linux binaries already, to be honest. Seems like there's already a lot of people using this who are compiling it for a native Linux build.

**Comment by Zal0** [comment]
The main reason why we cannot distribute Linux binaries is because there are a lot of distros.

**Comment by Takuyax** [comment]
For software distribution, the main difference between distros is that they use different packet managers, and different repositories. One problem could be availability of dependencies, though it seems SDCC is the only one? Raw GBDK x86 Linux binaries should work on any x86 distro though, especially since it doesn't have a GUI.

**Comment by Zal0** [comment]
So shouldn't the current macos binary work on Linux too according to that?

**Comment by Takuyax** [comment]
In theory that could be possible, but when I try to run the latest macos binaries it gives me this error:
`bash: ./lcc: cannot execute binary file: Exec format error`
Looking at the header in a hex editor, it seems macos doesn't use standard ELF binaries, but something proprietary.

**Comment by untoxa** [comment]
relevant binaries included into the release
