### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by ladecadence** [Zal0/gbdk-2020#5]
I downloaded the source code of the 3.0 version to build it on linux (Ubuntu 19.10).
First I compiled sdcc-4.0.0 from source and defined SDCCDIR environment variable accordingly.
Had some issues:

First, in the as/ and link/ subdirectories, the makefiles have a reference to as-gbz80.exe and link-gbz80.exe in the strip phase, so compilation fails (linux executables don't have an extension)

Then after the instalation with make install, when trying to compile the examples, had some problems with the paths, for example:

```
> make
../../bin/lcc -Wa-l -Wl-m -Wl-j -c -o galaxy.o galaxy.c
../../bin/lcc: /opt/gbdk/bin/SDCC/bin/sdcpp: No such file or directory
make: *** [Makefile:26: galaxy.o] Error 1
```
That's because sdcpp is installed in /opt/gbdk/bin/sdcc-4.0.0/bin/sdcpp and not on .../SDCC/...
Creating a symlink there works.
Then some examples also fail, but most work.

**Comment by Zal0** [comment]
Please update to the latest version
I fixed those bugs yesterday

**Comment by Zal0** [comment]
Sorry, it is my fault
The tag is not pointing to the last commit

**Comment by Zal0** [comment]
Now it's fixed. Thanks!

**Comment by Zal0** [comment]
Just to clarify. You no longer need that symlink, I changed a few lines on lcc linux to get the path from the command line
