### ISSUE TITLE
using initarand() and arand() leads to random code execution (gbdk 4.0, linux)

### ISSUE THREAD

**Issue by bbbbbr** [Zal0/gbdk-2020#53]
I haven't identified the specific problem, but it looks like calling initarand() and arand() will cause the current program to eventually start executing random code (at least in one case SP decrements endlessly). 

You can test this with the "rand.c" sample (or "dscan" sample which also uses arand). It typically takes about 10-13 iterations of the main loop before something bad happens. If it is changed to only use initrand() and rand() the problem does not appear to manifest.

At first glance it does not seem like changes to arand.s (vs 2.95) are the source of the problem.

For reference, the rand.c sample from the gbdk 2.95 built against 2.95 does not look like it has this problem.

**Comment by untoxa** [comment]
please make a minimal example, that demonstrates the problem.

**Comment by untoxa** [comment]
rand.c works fine

**Comment by bbbbbr** [comment]
The patch looks like it fixed the issue. Closing the ticket. 

Thanks!
