### ISSUE TITLE
GPL violation

### ISSUE THREAD

**Issue by ivanka2012** [Zal0/gbdk-2020#55]
So I noticed that some files say that they are GPL'd
https://github.com/Zal0/gbdk-2020/blob/develop/gbdk-lib/libc/__assert.c
https://github.com/Zal0/gbdk-2020/blob/develop/gbdk-lib/libc/_divslong.c
https://github.com/Zal0/gbdk-2020/blob/develop/gbdk-lib/libc/_divulong.c
However, the license is MIT, and GPL code in an MIT project is not legally possible

**Comment by JL2210** [comment]
They have an exception:
```
   As a special exception, if you link this library with other files,
   some of which are compiled with SDCC, to produce an executable,
   this library does not by itself cause the resulting executable to
   be covered by the GNU General Public License. This exception does
   not however invalidate any other reasons why the executable file
   might be covered by the GNU General Public License.
```

**Comment by ivanka2012** [comment]
So it can link to other stuff without violating anything. However, GPL still applies for the library, and I can't really find any reference inside the repository for the library's license

**Comment by untoxa** [comment]
that's pity

**Comment by bbbbbr** [comment]
ivanka2012:
> So it can link to other stuff without violating anything. However, GPL still applies for the library, and I can't really find any reference inside the repository for the library's license

According to the SDCC Wiki, almost all of the libraries (except some PIC features) also have the Linking Exception (LE).
https://sourceforge.net/p/sdcc/wiki/SDCC%20Library%20Licenses/

> The great majority of SDCC run-time libraries are licensed under the GPLv2+LE which allows linking of sdcc run time libraries with both free and non-free (proprietary, closed source) applications.
>
> The exception are PIC device libraries and header files which are derived from Microchip header (.inc) and linker script (.lkr) files. Microchip claims copyright on those, which might or might not be a valid claim. ....
