### ISSUE TITLE
How do I set the ROM's title?

### ISSUE THREAD

**Issue by Videogamer555** [Zal0/gbdk-2020#59]
I'm compiling a ROM with GBDK, but it doesn't save a game name in the header. How do I add a game name?

**Comment by untoxa** [comment]
-Wm-yn"TITLE"

**Comment by lighth7015** [comment]
That doesn't work. I get 
`lcc: -Wm-yn"TITLE" ignored`
when I try to supply a title.

**Comment by untoxa** [comment]
that's odd, because i see no problem myself:
```
../../../gbdk/bin/lcc -Wl-j -tempdir=obj -Wm-yn"GBDecompress" -o rom.gb src/key_num.c src/main.c                                                                src/key_num.c:                                                                                                                                                  
src/main.c:
```
do you use the latest binary release? what os?

**Comment by lighth7015** [comment]
I'm using Arch Linux, and my package version(s) are as follows-
```
Name            : gbdk-2020
Version         : 3.2-3
```
```
Name            : sdcc
Version         : 4.0.0-1
```

**Comment by untoxa** [comment]
no. you must take binary release from the link i gave you, or build everything yourself carefully following instructions in README.MD. your setup is broken and won't work.

**Comment by bbbbbr** [comment]
Also, if you use makebin directly, you must add a space between the argument and the title string:

For example with lcc `-Wm-yn"MYTITLE"` 
With makebin directly `-yn "MYTITLE"`
The maximum length (for makebin) is up to 15 characters, but may be shorter.

**Comment by untoxa** [comment]
that won't work with sdcc 4,0 either, @bbbbbr

**Comment by bbbbbr** [comment]
I just meant for the current GBDK-2020 & sdcc.

The difference in no space for LCC and space for makebin of the same argument may not be apparent at first.
