### ISSUE TITLE
lcc -S makes rel-file instead of binary rom

### ISSUE THREAD

**Issue by untoxa** [Zal0/gbdk-2020#60]
`lcc -S -o test.gb test.c`
produces test.gb which is not a binary rom, but an object file, that should be linked and then converted to the binary file with makebin.

**Comment by Zal0** [comment]
Hmmm.. what happens if you remove the '-o' option, because that's telling lcc to generate an object file no matter the extension you are pasing

**Comment by untoxa** [comment]
it's ok then. we might recognize the extension like it is done in the other cases, but that is a minor problem.
