### ISSUE TITLE
GBC Color Support

### ISSUE THREAD

**Issue by KoopintheHub** [Zal0/gbdk-2020#70]
I can't do background palettes for gbc because it pops up this error:
`C:/GBDK-2020/include/gb/cgb.h:40: syntax error: token -> 'first_palette' ; column 35`

Am I doing palettes wrong or is the header file wrong?

Palette code:
```
const UWORD warningPalettes[] = {
    RGB_WHITE, RGB_CYAN, RGB_RED, RGB_DARKGREEN
};
```
and I load the palette with:
`set_bkg_palette(0, 1, &warningPalettes[0]);`

**Comment by KoopintheHub** [comment]
Ok never mind, I was using banks for palettes. Its all fine now.
But I have an another problem. I can't use -Wl-yp0x143=0x80.

Is there an another argument that supports Game Boy Color?

**Comment by untoxa** [comment]
don't open issues that are not bugs or feature requests. look into CGB examples that come with GBDK-2020.

**Comment by KoopintheHub** [comment]
Sorry. I'll check.
