### ISSUE TITLE
lcc fails to compile into IHX

### ISSUE THREAD

**Issue by untoxa** [Zal0/gbdk-2020#71]
`lcc -o rom.ihx src/graphics.c src/main.c src/map2buf.c`

produces binary rom with the IHX extension, not Intel HEX.

**Comment by untoxa** [comment]
also:
missing `;` in https://github.com/Zal0/gbdk-2020/blob/develop/gbdk-support/lcc/gb.c#L221 in `".ihx.gb"` ?

**Comment by bbbbbr** [comment]
Is it correct that the makebin stage is not required if the output target is .gb?

I think this is what you are looking for. I can PR it if so. 
https://github.com/bbbbbr/gbdk-2020/commit/abce1fb79af04679e0167ac43b3c88aeb72cbba2

**Comment by untoxa** [comment]
yes, please.
