### ISSUE TITLE
list of possible improvements for current functions

### ISSUE THREAD

**Issue by DaKnig** [Zal0/gbdk-2020#9]
lets make a list of possible improvements and optimizations here. if at some point we'd get testing facility that can test the functions for expected behaviour, then we could test those.
https://gist.github.com/ISSOtm/c9b0efab55108ce63bfeb775525c8c2c/ - set_xxx_data family

**Comment by untoxa** [comment]
https://github.com/Zal0/gbdk-2020/commit/56fea902f35de82993b799cfc3faa8a68316ada3
