### ISSUE TITLE
"WIN32 Binaries" might be misleading

### ISSUE THREAD

**Issue by jserv** [Zal0/gbdk-2020#94]
I thought the term "WIN32 Binaries" might be misleading because they are actually built with [Mingw-w64](https://mingw-w64.org/). Here are my steps to discover:
```
wget https://github.com/Zal0/gbdk-2020/releases/latest/download/gbdk-win.zip
unzip gbdk-win.zip 
file gbdk/bin/sdcc.exe
```

It shows "PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows" while `lcc.exe` would be dedicated to 32-bit:
> gbdk/bin/lcc.exe: PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows

In other words, current "WIN32 Binaries" is the mixture of x86 and x86-64 executable files. In order to make "WIN32 Binaries" work, 64-bit Windows are required.

**Comment by bbbbbr** [comment]
It would be interesting to know how many users actually require 32 bit Windows. Probably not so many. But maybe there is no specific benefit to using the 64 bit Windows binaries vs 32 bit.

SDCC does appear to have snapshots builds for 32 bit Windows: sdcc-snapshot-i586-mingw32msvc-xxxxx.zip

**Comment by untoxa** [comment]
Fixed: https://github.com/Zal0/gbdk-2020/commit/208fb0f62d6040b590ac1afef50003d7fbf68cd4
