### ISSUE TITLE
?ASlink-Error-<cannot open> : "colorbar.ihx"

### ISSUE THREAD

**Issue by KoopintheHub** [Zal0/gbdk-2020#98]
I compile a GBC Example from the GBDK-2020 Color Bar Example folder

But it said a linking error: `?ASlink-Error-<cannot open> : "colorbar.ihx"`
Is there something missing, is it a bug or am I doing it wrong?

**Comment by bbbbbr** [comment]
* Which version of GBDK 2020 are you using?
* What operating system are you using, Linux or Windows?
* Are you compiling from the command line? If so, can you paste in the entire build process so that there is more context?

**Comment by KoopintheHub** [comment]
Ok it works now. I had to get GBDK-2020 4.0.1 (It's cause I never knew it was released 7 days ago)
